export const GET_VK_MATCHES = 'GET_VK_MATCHES';
export const VK_ON_PICKED_YEAR = 'VK_ON_PICKED_YEAR';
export const VK_ON_CHANGE_YEAR = 'VK_ON_PICKED_YEAR';
export const VK_EN_CONSTANTS = {
   FETCH_VK_EN_PROFILE_DATA: 'FETCH_VK_EN_PROFILE_DATA',
   FETCH_VK_EN_PROFILE_DATA_END_SUCCESS: 'FETCH_VK_EN_PROFILE_DATA_END_SUCCESS',
   FETCH_VK_EN_PROFILE_DATA_END_FAILURE: 'FETCH_VK_EN_PROFILE_DATA_END_FAILURE',
   GET_VK_EN_LOCAL_STORAGE_DATA: 'GET_VK_EN_LOCAL_STORAGE_DATA',
   GET_VK_EN_DB_PROFILE_DATA: 'GET_VK_EN_DB_PROFILE_DATA',
   GET_VK_EN_DB_EXTENDED_PROFILE_DATA: 'GET_VK_EN_DB_EXTENDED_PROFILE_DATA',
   INSERT_VK_EN_DB_PROFILE_DATA: 'INSERT_VK_EN_DB_PROFILE_DATA',
   UPDATE_VK_EN_DB_PROFILE_DATA: 'UPDATE_VK_EN_DB_PROFILE_DATA ',
};
